# recipe.py
QNA = {
    "Y": {
        "FREQ": "Q",
        "ADJUSTMENT": "",
        "REF_AREA": "KOR+CAN+USA+CHN+GBR+DEU+FRA+JPN+ITA+IND+MEX+IRL",
        "SECTOR": "S1",
        "COUNTERPART_SECTOR": "",
        "TRANSACTION": "B1GQ",
        "INSTR_ASSET": "",
        "ACTIVITY": "",
        "EXPENDITURE": "",
        "UNIT_MEASURE": "USD_PPP",
        "PRICE_BASE": "LR",
        "TRANSFORMATION": "",
        "TABLE_IDENTIFIER": ""
    },
    "C": {
        "FREQ": "Q",
        "ADJUSTMENT": "",
        "REF_AREA": "KOR+CAN+USA+CHN+GBR+DEU+FRA+JPN+ITA+IND+MEX+IRL",
        "SECTOR": "S1M",
        "COUNTERPART_SECTOR": "",
        "TRANSACTION": "P3",
        "INSTR_ASSET": "",
        "ACTIVITY": "",
        "EXPENDITURE": "",
        "UNIT_MEASURE": "USD_PPP",
        "PRICE_BASE": "LR",
        "TRANSFORMATION": "",
        "TABLE_IDENTIFIER": ""
    },
    "G": {
        "FREQ": "Q",
        "ADJUSTMENT": "",
        "REF_AREA": "KOR+CAN+USA+CHN+GBR+DEU+FRA+JPN+ITA+IND+MEX+IRL",
        "SECTOR": "S13",
        "COUNTERPART_SECTOR": "",
        "TRANSACTION": "P3",
        "INSTR_ASSET": "",
        "ACTIVITY": "",
        "EXPENDITURE": "",
        "UNIT_MEASURE": "USD_PPP",
        "PRICE_BASE": "LR",
        "TRANSFORMATION": "",
        "TABLE_IDENTIFIER": ""
    },
    "I": {
        "FREQ": "Q",
        "ADJUSTMENT": "",
        "REF_AREA": "KOR+CAN+USA+CHN+GBR+DEU+FRA+JPN+ITA+IND+MEX+IRL",
        "SECTOR": "S1",
        "COUNTERPART_SECTOR": "",
        "TRANSACTION": "P51G",
        "INSTR_ASSET": "",
        "ACTIVITY": "",
        "EXPENDITURE": "",
        "UNIT_MEASURE": "USD_PPP",
        "PRICE_BASE": "LR",
        "TRANSFORMATION": "",
        "TABLE_IDENTIFIER": ""
    },
    "EX": {
        "FREQ": "Q",
        "ADJUSTMENT": "",
        "REF_AREA": "KOR+CAN+USA+CHN+GBR+DEU+FRA+JPN+ITA+IND+MEX+IRL",
        "SECTOR": "S1",
        "COUNTERPART_SECTOR": "",
        "TRANSACTION": "P6",
        "INSTR_ASSET": "",
        "ACTIVITY": "",
        "EXPENDITURE": "",
        "UNIT_MEASURE": "USD_PPP",
        "PRICE_BASE": "LR",
        "TRANSFORMATION": "",
        "TABLE_IDENTIFIER": ""
    },
    "IM": {
        "FREQ": "Q",
        "ADJUSTMENT": "",
        "REF_AREA": "KOR+CAN+USA+CHN+GBR+DEU+FRA+JPN+ITA+IND+MEX+IRL",
        "SECTOR": "S1",
        "COUNTERPART_SECTOR": "",
        "TRANSACTION": "P7",
        "INSTR_ASSET": "",
        "ACTIVITY": "",
        "EXPENDITURE": "",
        "UNIT_MEASURE": "USD_PPP",
        "PRICE_BASE": "LR",
        "TRANSFORMATION": "",
        "TABLE_IDENTIFIER": ""
    }
}

